# Statistics Exercises

#### 1. How likely is it that you roll doubles when rolling two dice?

In [8]:
import numpy as np
import pandas as pd

np.random.seed(1234)

In [117]:
outcomes = [1,2,3,4,5,6]

n_dice = n_cols = 2
num_trials = n_rows = 1000000

data1 = np.random.choice(outcomes, num_trials * n_dice).reshape(num_trials, n_dice)
data1

array([[6, 4],
       [3, 3],
       [3, 4],
       ...,
       [6, 1],
       [6, 6],
       [2, 4]])

In [118]:
pd.DataFrame(data1).apply(lambda x: x[0] == x[1] in x.values, axis = 1).mean()

0.166396

#### 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? 

In [120]:
heads = 1
tails = 0
outcomes = [0,1]

n_trials = n_rows = 1000000
n_coins = n_cols = 8

data2 = np.random.choice(outcomes, n_trials * n_coins).reshape(n_rows, n_cols)
data2

array([[1, 0, 1, ..., 0, 0, 1],
       [0, 1, 1, ..., 0, 0, 1],
       [1, 1, 0, ..., 0, 0, 1],
       ...,
       [0, 1, 1, ..., 0, 1, 0],
       [1, 0, 1, ..., 0, 1, 1],
       [0, 0, 1, ..., 0, 1, 1]])

In [121]:
total_heads = data2.sum(axis = 1)
total_heads

array([3, 5, 5, ..., 4, 4, 5])

In [122]:
three_heads = (total_heads == 3).mean()
three_heads

0.218979

#### What is the probability of getting more than 3 heads?

In [125]:
more_than_three = (total_heads > 3).mean()
more_than_three

0.63656

#### 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [129]:
web = 3
data = 1
outcomes = [3,1]

prob_web = 0.75
prob_ds = 1 - prob_web

n_trials = n_rows = 1000000
n_alumns = n_cols = 2

data3 = np.random.choice(outcomes, n_trials * n_alumns, p = [prob_web, prob_ds]).reshape(n_rows, n_cols)
data3

array([[1, 3],
       [3, 1],
       [3, 3],
       ...,
       [3, 1],
       [1, 3],
       [3, 3]])

In [130]:
total_alums = data3.sum(axis = 1)
total_alums

array([4, 4, 6, ..., 4, 4, 6])

In [131]:
two_ds = (total_alums == 2).mean()
two_ds

0.062453

#### 4. Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?

In [135]:
n_trials = n_rows = 1000000
n_days = n_cols = 5

data4 = np.random.normal(3, 1.5, size = (n_trials, n_days))
data4

array([[2.12951076, 4.5405049 , 4.40586803, 3.38254733, 3.9331062 ],
       [2.61523523, 1.68529405, 3.27179368, 3.25797338, 3.00431835],
       [3.2463649 , 5.2759897 , 4.74195774, 2.79025333, 2.08085424],
       ...,
       [0.30179481, 5.74327071, 1.88828435, 2.71949137, 2.17850073],
       [2.8788624 , 2.9072502 , 3.39544213, 3.29222425, 3.89141057],
       [3.24488996, 2.90967169, 2.62904464, 2.91875247, 5.24297542]])

In [136]:
total_packs = data4.sum(axis = 1)
total_packs

array([18.39153722, 13.83461469, 18.13541991, ..., 12.83134197,
       16.36518956, 16.94533416])

In [139]:
poptarts = (total_packs < 17).mean()
poptarts

0.724418

#### 5. Compare Heights

    - Men have an average height of 178 cm and standard deviation of 8cm.
    - Women have a mean of 170, sd = 6cm.
    - If a man and woman are chosen at random, P(woman taller than man)?

In [143]:
n_trials = n_rows = 1000000
m_and_w = n_cols = 2

men_height = np.random.normal(178, 8, n_trials)
women_height = np.random.normal(170, 6, n_trials)

In [144]:
height_diff = np.subtract(men_height, women_height)
height_diff

array([ 8.66131688, 17.92880612, 11.51192133, ..., 10.759302  ,
        6.61063224, 15.38927982])

In [145]:
woman_taller = (height_diff < 0).mean()
woman_taller

0.212287

#### 6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 

In [149]:
prob_fail = 1/250
prob_success = 1 - prob_fail

outcomes = [0,1]

n_trials = n_rows = 1000000
n_downloads = n_cols = 50

data6 = np.random.choice(outcomes, n_trials * n_downloads, p = [prob_fail, prob_success]).reshape(n_rows, n_cols)
data6

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [150]:
installs50 = data6.sum(axis = 1)
installs50

array([50, 50, 50, ..., 50, 50, 50])

In [151]:
fails50 = (installs50 < 50).mean()
fails50

0.181616

#### 100 students?

In [152]:
prob_fail = 1/250
prob_success = 1 - prob_fail

outcomes = [0,1]

n_trials = n_rows = 1000000
n_downloads = n_cols = 100

data100 = np.random.choice(outcomes, n_trials * n_downloads, p = [prob_fail, prob_success]).reshape(n_rows, n_cols)
data100

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [153]:
installs100 = data100.sum(axis = 1)
installs100

array([100, 100, 100, ..., 100, 100, 100])

In [154]:
fails100 = (installs100 < 100).mean()
fails100

0.330868

#### What is the probability that we observe an installation issue within the first 150 students that download anaconda?

In [155]:
prob_fail = 1/250
prob_success = 1 - prob_fail

outcomes = [0,1]

n_trials = n_rows = 1000000
n_downloads = n_cols = 150

data150 = np.random.choice(outcomes, n_trials * n_downloads, p = [prob_fail, prob_success]).reshape(n_rows, n_cols)
data150

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [156]:
installs150 = data150.sum(axis = 1)
installs150

array([149, 148, 150, ..., 149, 150, 150])

In [157]:
fails150 = (installs150 < 150).mean()
fails150

0.45174

#### How likely is it that 450 students all download anaconda without an issue?

In [177]:
prob_fail = 1/250
prob_success = 1 - prob_fail

outcomes = [0,1]

n_trials = n_rows = 1000000
n_downloads = n_cols = 450

data450 = np.random.choice(outcomes, n_trials * n_downloads, p = [prob_fail, prob_success]).reshape(n_rows, n_cols)
data450

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 0, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [178]:
installs450 = data450.sum(axis = 1)
installs450

array([448, 445, 449, ..., 449, 446, 449])

In [179]:
fails450 = (installs450 < 450).mean()
fails450

0.834701

#### 7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

In [159]:
truck = 0.7
no_truck = 1 - truck

outcomes = [1,0]

n_trials = n_rows = 1000000
n_days = n_cols = 3

data7 = np.random.choice(outcomes, n_trials * n_days, p = [truck, no_truck]).reshape(n_rows, n_cols)
data7

array([[0, 1, 1],
       [0, 1, 1],
       [1, 0, 0],
       ...,
       [1, 1, 0],
       [0, 1, 1],
       [1, 1, 0]])

In [160]:
truck_totals = data7.sum(axis = 1)
truck_totals

array([2, 2, 1, ..., 2, 2, 2])

In [161]:
no_truck_chance = (truck_totals == 0).mean()
no_truck_chance

0.027127

#### How likely is it that a food truck will show up sometime this week?

In [162]:
truck = 0.7
no_truck = 1 - truck

outcomes = [1,0]

n_trials = n_rows = 1000000
n_days = n_cols = 7

data7days = np.random.choice(outcomes, n_trials * n_days, p = [truck, no_truck]).reshape(n_rows, n_cols)
data7days

array([[0, 0, 1, ..., 1, 1, 0],
       [1, 0, 1, ..., 1, 1, 1],
       [0, 1, 0, ..., 0, 1, 0],
       ...,
       [1, 1, 0, ..., 1, 1, 1],
       [1, 1, 1, ..., 0, 1, 1],
       [0, 0, 0, ..., 1, 1, 1]])

In [163]:
truck7days_totals = data7days.sum(axis = 1)
truck7days_totals

array([3, 6, 2, ..., 6, 6, 4])

In [164]:
truck7days_chance = (truck_totals > 0).mean()
truck7days_chance

0.972873

#### 8. If 23 people are in the same room, what are the odds that two of them share a birthday? 

In [165]:
bday = range(1,366)

n_trials = n_rows = 1000000
n_people = n_cols = 23

data8 = np.random.choice(bday, n_trials * n_people).reshape(n_rows, n_cols)
data8

array([[312,  25, 134, ..., 225, 356,  23],
       [238, 181, 144, ..., 149, 143,  34],
       [318, 118, 202, ...,  81, 209, 115],
       ...,
       [134, 282, 238, ..., 206, 153, 260],
       [365, 252,   3, ...,  35, 233, 145],
       [166, 309,  19, ..., 325,  25, 167]])

In [166]:
bdays23_df = pd.DataFrame(data8)
bdays23_df.head()

0    1    2    3    4    5    6    7    8    9   ...   13   14   15   16  \
0  312   25  134  208  117  147  259  165   44  276  ...  137   92  334  146   
1  238  181  144   50  360   72  156  165  223  363  ...  160  308  337  360   
2  318  118  202  239  145  115  365   96  126  356  ...    2  333  220  217   
3   70  340  142  301   46   73  213   73  339  270  ...  321   42   68   21   
4   55  193  156  325  190  233  205  117   31  284  ...  301  156  329   10   

    17   18   19   20   21   22  
0  286  328  112  225  356   23  
1   16  258  358  149  143   34  
2    8  116  120   81  209  115  
3  181  249  263   84   40  189  
4   86  342   21   77  278  106  

[5 rows x 23 columns]

In [167]:
same_day23 = bdays23_df.nunique(axis = 1)
same_day23

0         23
1         22
2         22
3         22
4         22
          ..
999995    23
999996    22
999997    22
999998    23
999999    22
Length: 1000000, dtype: int64

In [168]:
same23 = (same_day23 < 23).mean()
same23

0.506959

#### What if it's 20 people?

In [169]:
bday = range(1,366)

n_trials = n_rows = 1000000
n_people = n_cols = 20

data20 = np.random.choice(bday, n_trials * n_people).reshape(n_rows, n_cols)
data20

array([[148, 263, 182, ...,  24,  23,  18],
       [109, 186,  27, ..., 124, 356, 145],
       [120, 158, 223, ...,  44, 320,  39],
       ...,
       [ 70, 362, 231, ..., 214, 283, 210],
       [ 19, 231, 342, ..., 262, 156, 311],
       [326,  33, 198, ...,   9, 316, 137]])

In [170]:
bdays20_df = pd.DataFrame(data20)
bdays20_df.head()

0    1    2    3    4    5    6    7    8    9    10   11   12   13   14  \
0  148  263  182   86  229   76  146  212  175  331  222  181  254  106   29   
1  109  186   27   86  198  235   75   65  177   34   22  299  156  196  140   
2  120  158  223  253   10   18  175  102   61  265  329  321  353  115  104   
3   72  152  180  358  226  275  300  270  309  262  218  176   42  206  313   
4  220  127  132   95  122  263   80  251  357   10   31  107  142  244   83   

    15   16   17   18   19  
0  291    7   24   23   18  
1  261  326  124  356  145  
2  106  152   44  320   39  
3   48  102  325  312  246  
4   12  220    9  284  220

In [171]:
same_day20 = bdays20_df.nunique(axis = 1)
same_day20

0         20
1         20
2         20
3         20
4         18
          ..
999995    19
999996    20
999997    20
999998    19
999999    20
Length: 1000000, dtype: int64

In [172]:
same20 = (same_day20 < 20).mean()
same20

0.411682

####  40?

In [173]:
bday = range(1,366)

n_trials = n_rows = 1000000
n_people = n_cols = 40

data40 = np.random.choice(bday, n_trials * n_people).reshape(n_rows, n_cols)
data40

array([[362, 133, 171, ..., 111,  70, 313],
       [106, 194, 308, ...,  34, 245, 256],
       [130, 154,  46, ..., 183, 121,  12],
       ...,
       [358, 121, 163, ..., 255, 343, 199],
       [329,  95, 267, ..., 252,  36, 121],
       [261,   1,  31, ...,  85, 279, 105]])

In [174]:
bdays40_df = pd.DataFrame(data40)
bdays40_df.head()

0    1    2    3    4    5    6    7    8    9   ...   30   31   32   33  \
0  362  133  171    3  270  300   68  133  106  113  ...  282   29  209  143   
1  106  194  308  149  243  111  104   88   76  226  ...  302   55  307   17   
2  130  154   46  191   70  274  178  132   63   85  ...  131   84  346   69   
3  317  264    3    7   96  320  290  308   20  124  ...   74  181   95  166   
4  275  216  265  316  337  182  280  187   34  325  ...  189   29  261  157   

    34   35   36   37   38   39  
0   74  347  134  111   70  313  
1   93  283  138   34  245  256  
2  192   61  153  183  121   12  
3  124  324   34  260  348   31  
4   32    3  305  162  302  260  

[5 rows x 40 columns]

In [175]:
same_day40 = bdays40_df.nunique(axis = 1)
same_day40

0         37
1         38
2         39
3         39
4         40
          ..
999995    36
999996    40
999997    38
999998    38
999999    37
Length: 1000000, dtype: int64

In [176]:
same40 = (same_day40 < 40).mean()
same40

0.891344