# Statistics Exercises

#### 1. How likely is it that you roll doubles when rolling two dice?

In [8]:
import numpy as np
import pandas as pd

np.random.seed(1234)

In [75]:
possible_outcomes = [1,2,3,4,5,6]

n_dice = n_cols = 2
num_trials = n_rows = 10000

data1 = np.random.choice(possible_outcomes, num_trials * n_dice).reshape(num_trials, n_dice)
data1

array([[5, 6],
       [4, 1],
       [5, 6],
       ...,
       [5, 5],
       [4, 5],
       [3, 3]])

In [76]:
pd.DataFrame(data1).apply(lambda x: x[0] == x[1] in x.values, axis = 1).mean()

0.1683

#### 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [77]:
heads = 1
tails = 0
outcomes = [0,1]

n_trials = n_rows = 10000
n_coins = n_cols = 8

data2 = np.random.choice(outcomes, n_trials * n_coins).reshape(n_rows, n_cols)
data2

array([[0, 1, 0, ..., 1, 1, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 1, 0, 0],
       ...,
       [1, 0, 1, ..., 1, 1, 1],
       [1, 0, 1, ..., 0, 1, 0],
       [1, 0, 1, ..., 0, 0, 1]])

In [78]:
total_heads = data2.sum(axis = 1)
total_heads

array([4, 2, 3, ..., 5, 5, 5])

In [79]:
three_heads = (total_heads == 3).mean()
three_heads

0.219

In [80]:
more_than_three = (total_heads > 3).mean()
more_than_three

0.636

#### 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [81]:
web = 3
data = 1
outcomes = [3,1]

prob_web = 0.75
prob_ds = 1 - prob_web

n_trials = n_rows = 10000
n_billboards = n_cols = 2

data3 = np.random.choice(outcomes, n_trials * n_billboards, p = [prob_web, prob_ds]).reshape(n_rows, n_cols)
data3

array([[3, 1],
       [3, 3],
       [3, 3],
       ...,
       [3, 3],
       [3, 3],
       [1, 1]])

In [82]:
total_alums = data3.sum(axis = 1)
total_alums

array([4, 6, 6, ..., 6, 6, 2])

In [83]:
two_ds = (total_alums == 2).mean()
two_ds

0.0656

#### 4. Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?

In [84]:
n_trials = n_rows = 10000
n_days = n_cols = 5

data4 = np.round(np.random.normal(3, 1.5, size = (n_trials, n_days)))
data4

array([[3., 6., 3., 2., 1.],
       [1., 1., 2., 5., 5.],
       [2., 4., 1., 4., 2.],
       ...,
       [3., 1., 4., 1., 4.],
       [4., 1., 2., 3., 6.],
       [2., 3., 3., 4., 1.]])

In [85]:
total_packs = data4.sum(axis = 1)
total_packs

array([15., 14., 13., ..., 13., 16., 13.])

In [86]:
poptarts = (total_packs < 17).mean()
poptarts

0.6722

#### 5. Compare Heights

    - Men have an average height of 178 cm and standard deviation of 8cm.
    - Women have a mean of 170, sd = 6cm.
    - If a man and woman are chosen at random, P(woman taller than man)?

In [87]:
n_trials = n_rows = 10000
m_and_w = n_cols = 2

men_height = np.random.normal(178, 8, n_trials)
women_height = np.random.normal(170, 6, n_trials)

np.column_stack((men_height, women_height))

array([[190.69220732, 175.9641529 ],
       [184.68459948, 172.3926078 ],
       [169.36440389, 162.90068267],
       ...,
       [170.55689378, 167.3219657 ],
       [179.00141315, 160.03127155],
       [173.814757  , 173.60504601]])

In [88]:
height_diff = np.subtract(men_height, women_height)
height_diff

array([14.72805441, 12.29199168,  6.46372122, ...,  3.23492808,
       18.97014159,  0.209711  ])

In [89]:
woman_taller = (height_diff < 0).mean()
woman_taller

0.2144

#### 6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 

In [90]:
prob_fail = 1/250
prob_success = 1 - prob_fail

outcomes = [0,1]

n_trials = n_rows = 10000
n_downloads = n_cols = 50

data6 = np.random.choice(outcomes, n_trials * n_downloads, p = [prob_fail, prob_success]).reshape(n_rows, n_cols)
data6

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 0]])

In [93]:
installs50 = data6.sum(axis = 1)
installs50

array([50, 50, 50, ..., 50, 48, 49])

In [94]:
fails50 = (installs50 < 50).mean()
fails50

0.1806

#### 100 students?

In [95]:
prob_fail = 1/250
prob_success = 1 - prob_fail

outcomes = [0,1]

n_trials = n_rows = 10000
n_downloads = n_cols = 100

data100 = np.random.choice(outcomes, n_trials * n_downloads, p = [prob_fail, prob_success]).reshape(n_rows, n_cols)
data100

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [96]:
installs100 = data100.sum(axis = 1)
installs100

array([100, 100, 100, ..., 100,  98, 100])

In [97]:
fails100 = (installs100 < 100).mean()
fails100

0.3335

#### What is the probability that we observe an installation issue within the first 150 students that download anaconda?

In [98]:
prob_fail = 1/250
prob_success = 1 - prob_fail

outcomes = [0,1]

n_trials = n_rows = 10000
n_downloads = n_cols = 150

data150 = np.random.choice(outcomes, n_trials * n_downloads, p = [prob_fail, prob_success]).reshape(n_rows, n_cols)
data150

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [99]:
installs150 = data150.sum(axis = 1)
installs150

array([150, 149, 149, ..., 150, 150, 150])

In [100]:
fails150 = (installs150 < 150).mean()
fails150

0.4507

#### 7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

In [57]:
truck = 0.7
no_truck = 1 - truck

outcomes = [1,0]

n_trials = n_rows = 10000
n_days = n_cols = 3

data7 = np.random.choice(outcomes, n_trials * n_days, p = [truck, no_truck]).reshape(n_rows, n_cols)
data7

array([[0, 1, 1],
       [0, 1, 1],
       [0, 1, 1],
       ...,
       [1, 1, 1],
       [1, 1, 1],
       [0, 1, 1]])

In [58]:
truck_totals = data7.sum(axis = 1)
truck_totals

array([2, 2, 2, ..., 3, 3, 2])

In [103]:
no_truck_chance = (truck_totals == 0).mean()
no_truck_chance

0.0265

#### How likely is it that a food truck will show up sometime this week?

In [101]:
truck = 0.7
no_truck = 1 - truck

outcomes = [1,0]

n_trials = n_rows = 10000
n_days = n_cols = 7

data7days = np.random.choice(outcomes, n_trials * n_days, p = [truck, no_truck]).reshape(n_rows, n_cols)
data7days

array([[1, 1, 1, ..., 0, 0, 0],
       [1, 0, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 0, 1, 1],
       ...,
       [0, 0, 1, ..., 1, 1, 1],
       [1, 1, 0, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 0, 0]])

In [102]:
truck7days_totals = data7days.sum(axis = 1)
truck7days_totals

array([4, 6, 5, ..., 4, 6, 5])

In [104]:
truck7days_chance = (truck_totals > 0).mean()
truck7days_chance

0.9735

#### 8. If 23 people are in the same room, what are the odds that two of them share a birthday? 

In [60]:
bday = range(1,366)

n_trials = n_rows = 10000
n_people = n_cols = 23

data8 = np.random.choice(bday, n_trials * n_people).reshape(n_rows, n_cols)
data8

array([[ 91, 347, 263, ...,  17,  64, 289],
       [180, 143, 298, ...,  13, 364, 134],
       [ 73, 361,  88, ...,  36,  24, 113],
       ...,
       [161,  84, 253, ...,  54, 136, 276],
       [218, 167,  83, ..., 202, 181, 229],
       [281, 115, 340, ..., 149, 327, 146]])

In [66]:
bdays23_df = pd.DataFrame(data8)
bdays23_df.head()

0    1    2    3    4    5    6    7    8    9   ...   13   14   15   16  \
0   91  347  263  266  324  186  209  349  266  118  ...  229   27   27   46   
1  180  143  298  115  110  251   66   86  118  265  ...  256  106  246  341   
2   73  361   88  110  240  361   76  131  153    4  ...  305  297   36  122   
3  309  224  327  165  321   82  190  138  325  263  ...  133  301  296  230   
4  227  289  256  218  299   23  365   41  108  129  ...  100  293  338   65   

    17   18   19   20   21   22  
0  257  246  108   17   64  289  
1  179  273  304   13  364  134  
2  282   67  111   36   24  113  
3   32  292  129  200  263  341  
4  169  305  361  247  233  276  

[5 rows x 23 columns]

In [67]:
same_day23 = bdays23_df.nunique(axis = 1)
same_day23

0       21
1       23
2       21
3       22
4       23
        ..
9995    21
9996    21
9997    23
9998    22
9999    22
Length: 10000, dtype: int64

In [68]:
same23 = (same_day23 < 23).mean()
same23

0.5166

#### What if it's 20 people?

In [105]:
bday = range(1,366)

n_trials = n_rows = 10000
n_people = n_cols = 20

data20 = np.random.choice(bday, n_trials * n_people).reshape(n_rows, n_cols)
data20

array([[321, 226, 144, ..., 334,  81,  81],
       [349,  80,  75, ..., 300, 348, 292],
       [362, 322,  98, ..., 288, 126, 216],
       ...,
       [ 59, 195, 255, ..., 153, 130, 103],
       [349, 102,  89, ...,  43,  68,  92],
       [296,   4,  63, ..., 307, 299, 114]])

In [106]:
bdays20_df = pd.DataFrame(data20)
bdays20_df.head()

0    1    2    3    4    5    6    7    8    9    10   11   12   13   14  \
0  321  226  144  315  134   92   68   45  314  164  141  343   58  154   27   
1  349   80   75  321  133  127  104  353  225   12  142  206  295   86  297   
2  362  322   98  180  329  189  311  241   83  180  205  124  316  305  311   
3   73  183  293  246  290  130  200    3  322  239   80  107  108  111  221   
4   17  228   21  203   78  298  299  222  325  308  265  177  298  304   75   

    15   16   17   18   19  
0   61  215  334   81   81  
1  240  276  300  348  292  
2    2  225  288  126  216  
3  113  267  245  215  345  
4  310   50  111   77   94

In [107]:
same_day20 = bdays20_df.nunique(axis = 1)
same_day20

0       19
1       20
2       18
3       20
4       19
        ..
9995    20
9996    19
9997    20
9998    20
9999    17
Length: 10000, dtype: int64

In [108]:
same20 = (same_day20 < 20).mean()
same20

0.4164

####  40?

In [109]:
bday = range(1,366)

n_trials = n_rows = 10000
n_people = n_cols = 40

data40 = np.random.choice(bday, n_trials * n_people).reshape(n_rows, n_cols)
data40

array([[ 56,  32,  81, ..., 220, 164, 159],
       [203, 141, 152, ..., 285,  13, 179],
       [ 45, 194, 214, ..., 263, 101,  26],
       ...,
       [ 45,  19,  31, ..., 284, 184,  11],
       [ 73, 262, 279, ..., 256, 334, 201],
       [158,  74,  90, ...,  66,   7, 233]])

In [110]:
bdays40_df = pd.DataFrame(data40)
bdays40_df.head()

0    1    2    3    4    5    6    7    8    9   ...   30   31   32   33  \
0   56   32   81  365  328   68  129  158   48  348  ...  161   91   74  351   
1  203  141  152  242  343   45  226   12  117  186  ...  284  146  115  135   
2   45  194  214  283  347  147   31   37   76  312  ...  310  309   62   37   
3  262  111  216  271  263   86  296   43  330  122  ...  237  242  219  301   
4  155  246  107  274  290  220   62   71   50   30  ...   70  230  301  161   

    34   35   36   37   38   39  
0   45   20  362  220  164  159  
1  308  344   71  285   13  179  
2   27   70   40  263  101   26  
3  160  236  362  152  190  108  
4  153  328  303  180  334  320  

[5 rows x 40 columns]

In [111]:
same_day40 = bdays40_df.nunique(axis = 1)
same_day40

0       37
1       39
2       37
3       39
4       38
        ..
9995    39
9996    38
9997    36
9998    40
9999    39
Length: 10000, dtype: int64

In [112]:
same40 = (same_day40 < 40).mean()
same40

0.8936